FROM ubuntu:20.04
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y git python3 python3-pip gedit
RUN pip3 install pandas numpy jupyter tqdm matplotlib
RUN echo "deb [ arch=amd64 ] https://downloads.skewed.de/apt focal main" >> /etc/apt/sources.list && \
    apt-key adv --keyserver keys.openpgp.org --recv-key 612DEFB798507F25 && \
    apt update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y python3-graph-tool
